build:
    environment:
        php:
            version: 8.0
            ini:
                xdebug.mode: coverage
    nodes:
        standalone-tests:
            tests:
                before:
                    - mkdir build
                    - mkdir build/logs
                override:
                    - command: php vendor/bin/phpunit
                      coverage:
                          file: build/logs/coverage.clover
                          format: clover
build_failure_conditions:
    - 'elements.rating(<= D).new.exists'
    - 'project.metric_change("scrutinizer.test_coverage", < -0.05)'
    - 'project.metric("scrutinizer.test_coverage", < 0.70)'
    - 'project.metric("scrutinizer.quality", < 8)'